# Generated by Django 3.2.19 on 2023-08-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
