# Generated by Django 3.2.19 on 2023-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0002_appuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='usernamerand', max_length=255),
            preserve_default=False,
        ),
    ]
