# Generated by Django 3.2.19 on 2023-08-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0004_remove_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='appuser',
        ),
        migrations.RemoveField(
            model_name='followings',
            name='appuser',
        ),
        migrations.AddField(
            model_name='followers',
            name='current_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers_current_user', to='mysocialapp.appuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers_follower', to='mysocialapp.appuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followings',
            name='current_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followings_current_user', to='mysocialapp.appuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followings',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followings_following', to='mysocialapp.appuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_current_user', to='mysocialapp.appuser')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_request', to='mysocialapp.appuser')),
            ],
        ),
    ]
