# Generated by Django 3.2.19 on 2023-08-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0005_auto_20230827_0652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('current_user', 'follower')},
        ),
        migrations.AlterUniqueTogether(
            name='followings',
            unique_together={('current_user', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('current_user', 'request')},
        ),
    ]
