# Generated by Django 3.2.19 on 2023-08-30 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0006_auto_20230827_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='requests',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='request',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
