# Generated by Django 3.2.19 on 2024-01-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
