# Generated by Django 3.2.19 on 2024-01-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0011_gallery_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='post_video',
            new_name='post_media',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='post_image',
        ),
    ]
