# Generated by Django 3.2.19 on 2024-01-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0013_auto_20240117_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('treatment', 'Treatment Options'), ('lifestyle', 'Lifestyle Adjustments'), ('emotional', 'Emotional Support'), ('challenges', 'Daily Challenges')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
