# Generated by Django 3.2.19 on 2024-01-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0015_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesters', to='mysocialapp.appuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mysocialapp.appuser')),
            ],
            options={
                'unique_together': {('user', 'requester')},
            },
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
