# Generated by Django 3.2.19 on 2024-01-25 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0016_auto_20240124_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_users', to='mysocialapp.appuser'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('requested_user', 'requester')},
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
