# Generated by Django 3.2.19 on 2024-01-30 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0019_chatmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='group',
            field=models.CharField(choices=[('patient', 'patient'), ('volunteer', 'volunteer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VolunteerHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preferred_date_time', models.DateTimeField()),
                ('category', models.CharField(choices=[('grocery', 'Help with groceries'), ('house_cleaning', 'Help with house cleaning'), ('emotional', 'Provide emotional help'), ('others', 'Help with specific tasks')], max_length=20)),
                ('volunteer_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='At least 1 volunteer is required.'), django.core.validators.MaxValueValidator(5, message='No more than 5 volunteers allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='mysocialapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteeredHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='mysocialapp.appuser')),
                ('volunteer_help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_helps', to='mysocialapp.volunteerhelp')),
            ],
            options={
                'unique_together': {('volunteer_help', 'user')},
            },
        ),
    ]
