# Generated by Django 3.2.19 on 2024-02-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0020_auto_20240130_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerhelp',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=3),
            preserve_default=False,
        ),
    ]
