# Generated by Django 3.2.19 on 2024-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0021_volunteerhelp_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeredhelp',
            name='description_field_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteeredhelp',
            name='duration_field_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteeredhelp',
            name='preferred_date_time_field_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteeredhelp',
            name='title_field_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteeredhelp',
            name='volunteer_limit_field_changed',
            field=models.BooleanField(default=False),
        ),
    ]
