# Generated by Django 3.2.19 on 2024-03-14 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0023_diseaseoverview_patientstory_researchupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeredhelp',
            name='location_field_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerhelp',
            name='location',
            field=models.CharField(choices=[('Sembawang', 'Sembawang'), ('Woodlands', 'Woodlands'), ('Yishun', 'Yishun'), ('Ang Mo Kio', 'Ang Mo Kio'), ('Hougang', 'Hougang'), ('Punggol', 'Punggol'), ('Sengkang', 'Sengkang'), ('Serangoon', 'Serangoon'), ('Bedok', 'Bedok'), ('Pasir Ris', 'Pasir Ris'), ('Tampines', 'Tampines'), ('Bukit Batok', 'Bukit Batok'), ('Bukit Panjang', 'Bukit Panjang'), ('Choa Chu Kang', 'Choa Chu Kang'), ('Clementi', 'Clementi'), ('Jurong East', 'Jurong East'), ('Jurong West', 'Jurong West'), ('Tengah', 'Tengah'), ('Central', 'Central'), ('Bishan', 'Bishan'), ('Bukit Merah', 'Bukit Merah'), ('Bukit Timah', 'Bukit Timah'), ('Central Area', 'Central Area'), ('Geylang', 'Geylang'), ('Kallang/ Whampoa', 'Kallang/ Whampoa'), ('Marine Parade', 'Marine Parade'), ('Queenstown', 'Queenstown'), ('Toa Payoh', 'Toa Payoh')], default=django.utils.timezone.now, help_text='Select a location in Singapore', max_length=50),
            preserve_default=False,
        ),
    ]
